spring.application.name=geektext

# Database connection (values come from environment variables - dont put database values here, because they gonna be publicly visible on GitHub)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Tables are created by database/schema.sql, not by hibernate
spring.jpa.hibernate.ddl-auto=none